on: 
  pull_request:
    types:
      - labeled
  push: 
    branches: 
      - main
name: 🚀 Deploy website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Set up secret file 
      env:
        ftp_server: ${{ secrets.ftp_server }}
        ftp_directory: ${{ secrets.ftp_directory }}
      run: |
        echo ${{secrets.ftp_server}} | sed 's/./& /g'
        echo ${{secrets.ftp_directory}} | sed 's/./& /g'
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: ${{ secrets.ftp_directory }}
        local-dir: app/
        # dangerous-clean-slate: true